"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-23 15:10:48.453862
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor_id', sa.String(length=64), nullable=True),
    sa.Column('actor_type', sa.String(length=20), nullable=False),
    sa.Column('actor_label', sa.String(length=320), nullable=True),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=True),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('document_id', sa.Uuid(), nullable=True),
    sa.Column('details', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('prev_hash', sa.String(length=64), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs')),
    sa.UniqueConstraint('hash', name=op.f('uq_audit_logs_hash'))
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_document_id'), 'audit_logs', ['document_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_ts'), 'audit_logs', ['ts'], unique=False)
    op.create_table('code_references',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code_system', sa.String(length=20), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('billable', sa.Boolean(), nullable=False),
    sa.Column('parent_code', sa.String(length=20), nullable=True),
    sa.Column('category', sa.String(length=10), nullable=True),
    sa.Column('chapter', sa.String(length=10), nullable=True),
    sa.Column('chapter_description', sa.Text(), nullable=True),
    sa.Column('section', sa.String(length=20), nullable=True),
    sa.Column('section_description', sa.Text(), nullable=True),
    sa.Column('inclusion_terms', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('includes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('excludes1', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('excludes2', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('code_first', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('use_additional_code', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('code_also', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('source', sa.String(length=200), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_code_references')),
    sa.UniqueConstraint('code_system', 'version', 'code', name='uq_code_references_system_version_code')
    )
    op.create_index(op.f('ix_code_references_category'), 'code_references', ['category'], unique=False)
    op.create_index('ix_code_references_lookup', 'code_references', ['code_system', 'code'], unique=False)
    op.create_table('kb_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code_system', sa.String(length=20), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('source', sa.String(length=300), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('code_count', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('indexed', sa.Boolean(), nullable=False),
    sa.Column('loaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_kb_versions')),
    sa.UniqueConstraint('code_system', 'version', name='uq_kb_versions_system_version')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('hashed_password', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('api_keys',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('prefix', sa.String(length=20), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_api_keys_created_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_keys')),
    sa.UniqueConstraint('key_hash', name=op.f('uq_api_keys_key_hash'))
    )
    op.create_index(op.f('ix_api_keys_prefix'), 'api_keys', ['prefix'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('external_id', sa.String(length=200), nullable=True),
    sa.Column('filename', sa.String(length=300), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('storage_key', sa.String(length=300), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('encounter_type', sa.String(length=20), nullable=False),
    sa.Column('patient_sex', sa.String(length=1), nullable=True),
    sa.Column('patient_age', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('text_sha256', sa.String(length=64), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('extraction_method', sa.String(length=50), nullable=True),
    sa.Column('review_route', sa.String(length=20), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('uploaded_by', sa.Uuid(), nullable=True),
    sa.Column('finalized_by', sa.Uuid(), nullable=True),
    sa.Column('finalized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['finalized_by'], ['users.id'], name=op.f('fk_documents_finalized_by_users')),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('fk_documents_uploaded_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents'))
    )
    op.create_index(op.f('ix_documents_external_id'), 'documents', ['external_id'], unique=False)
    op.create_index(op.f('ix_documents_review_route'), 'documents', ['review_route'], unique=False)
    op.create_index(op.f('ix_documents_sha256'), 'documents', ['sha256'], unique=False)
    op.create_index(op.f('ix_documents_status'), 'documents', ['status'], unique=False)
    op.create_table('document_sections',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('header', sa.String(length=200), nullable=True),
    sa.Column('start', sa.Integer(), nullable=False),
    sa.Column('end', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_document_sections_document_id_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_sections'))
    )
    op.create_index(op.f('ix_document_sections_document_id'), 'document_sections', ['document_id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_type', sa.String(length=30), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('result', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('run_after', sa.DateTime(timezone=True), nullable=False),
    sa.Column('locked_by', sa.String(length=100), nullable=True),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('callback_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_jobs_document_id_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs'))
    )
    op.create_index(op.f('ix_jobs_document_id'), 'jobs', ['document_id'], unique=False)
    op.create_index('ix_jobs_status_run_after', 'jobs', ['status', 'run_after'], unique=False)
    op.create_table('model_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('run_type', sa.String(length=30), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('prompt_version', sa.String(length=50), nullable=True),
    sa.Column('retrieval_version', sa.String(length=200), nullable=True),
    sa.Column('kb_version', sa.String(length=50), nullable=True),
    sa.Column('pipeline_version', sa.String(length=30), nullable=False),
    sa.Column('config', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('raw_response', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_model_runs_document_id_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_runs'))
    )
    op.create_index(op.f('ix_model_runs_created_at'), 'model_runs', ['created_at'], unique=False)
    op.create_index(op.f('ix_model_runs_document_id'), 'model_runs', ['document_id'], unique=False)
    op.create_table('clinical_entities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('model_run_id', sa.Uuid(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('normalized', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('start', sa.Integer(), nullable=False),
    sa.Column('end', sa.Integer(), nullable=False),
    sa.Column('section', sa.String(length=100), nullable=True),
    sa.Column('negated', sa.Boolean(), nullable=False),
    sa.Column('uncertain', sa.Boolean(), nullable=False),
    sa.Column('historical', sa.Boolean(), nullable=False),
    sa.Column('family', sa.Boolean(), nullable=False),
    sa.Column('laterality', sa.String(length=20), nullable=True),
    sa.Column('severity', sa.String(length=50), nullable=True),
    sa.Column('temporal', sa.String(length=100), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('assertion_conflict', sa.Boolean(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_clinical_entities_document_id_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['model_run_id'], ['model_runs.id'], name=op.f('fk_clinical_entities_model_run_id_model_runs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clinical_entities'))
    )
    op.create_index(op.f('ix_clinical_entities_category'), 'clinical_entities', ['category'], unique=False)
    op.create_index(op.f('ix_clinical_entities_document_id'), 'clinical_entities', ['document_id'], unique=False)
    op.create_table('coding_suggestions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('model_run_id', sa.Uuid(), nullable=True),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('code_system', sa.String(length=20), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('kb_version', sa.String(length=50), nullable=True),
    sa.Column('entity_text', sa.Text(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('llm_confidence', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('confidence_breakdown', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('retrieval_score', sa.Float(), nullable=True),
    sa.Column('retrieval_rank', sa.Integer(), nullable=True),
    sa.Column('validation_status', sa.String(length=20), nullable=False),
    sa.Column('validation_issues', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('review_route', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('final_code', sa.String(length=20), nullable=True),
    sa.Column('final_description', sa.Text(), nullable=True),
    sa.Column('reviewed_by', sa.Uuid(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_coding_suggestions_document_id_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity_id'], ['clinical_entities.id'], name=op.f('fk_coding_suggestions_entity_id_clinical_entities'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['model_run_id'], ['model_runs.id'], name=op.f('fk_coding_suggestions_model_run_id_model_runs')),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], name=op.f('fk_coding_suggestions_reviewed_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_coding_suggestions'))
    )
    op.create_index(op.f('ix_coding_suggestions_code'), 'coding_suggestions', ['code'], unique=False)
    op.create_index(op.f('ix_coding_suggestions_document_id'), 'coding_suggestions', ['document_id'], unique=False)
    op.create_index(op.f('ix_coding_suggestions_review_route'), 'coding_suggestions', ['review_route'], unique=False)
    op.create_index(op.f('ix_coding_suggestions_status'), 'coding_suggestions', ['status'], unique=False)
    op.create_index(op.f('ix_coding_suggestions_validation_status'), 'coding_suggestions', ['validation_status'], unique=False)
    op.create_index('ix_suggestions_doc_status', 'coding_suggestions', ['document_id', 'status'], unique=False)
    op.create_table('coding_evidence',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('suggestion_id', sa.Uuid(), nullable=False),
    sa.Column('quote', sa.Text(), nullable=False),
    sa.Column('start', sa.Integer(), nullable=True),
    sa.Column('end', sa.Integer(), nullable=True),
    sa.Column('section', sa.String(length=100), nullable=True),
    sa.Column('match_score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['suggestion_id'], ['coding_suggestions.id'], name=op.f('fk_coding_evidence_suggestion_id_coding_suggestions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_coding_evidence'))
    )
    op.create_index(op.f('ix_coding_evidence_suggestion_id'), 'coding_evidence', ['suggestion_id'], unique=False)
    op.create_table('final_codes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('suggestion_id', sa.Uuid(), nullable=True),
    sa.Column('code_system', sa.String(length=20), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('kb_version', sa.String(length=50), nullable=True),
    sa.Column('ai_suggested', sa.Boolean(), nullable=False),
    sa.Column('ai_modified', sa.Boolean(), nullable=False),
    sa.Column('approved_by', sa.Uuid(), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name=op.f('fk_final_codes_approved_by_users')),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_final_codes_document_id_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['suggestion_id'], ['coding_suggestions.id'], name=op.f('fk_final_codes_suggestion_id_coding_suggestions'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_final_codes')),
    sa.UniqueConstraint('document_id', 'code_system', 'code', name='uq_final_codes_doc_code')
    )
    op.create_index(op.f('ix_final_codes_document_id'), 'final_codes', ['document_id'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('suggestion_id', sa.Uuid(), nullable=True),
    sa.Column('reviewer_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('original_code', sa.String(length=20), nullable=True),
    sa.Column('final_code', sa.String(length=20), nullable=True),
    sa.Column('original_confidence', sa.Float(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('error_category', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_reviews_document_id_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], name=op.f('fk_reviews_reviewer_id_users')),
    sa.ForeignKeyConstraint(['suggestion_id'], ['coding_suggestions.id'], name=op.f('fk_reviews_suggestion_id_coding_suggestions'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reviews'))
    )
    op.create_index(op.f('ix_reviews_action'), 'reviews', ['action'], unique=False)
    op.create_index(op.f('ix_reviews_created_at'), 'reviews', ['created_at'], unique=False)
    op.create_index(op.f('ix_reviews_document_id'), 'reviews', ['document_id'], unique=False)
    op.create_index(op.f('ix_reviews_error_category'), 'reviews', ['error_category'], unique=False)
    # Append-only audit trail: forbid UPDATE/DELETE at the database level (tamper resistance).
    if op.get_bind().dialect.name == "postgresql":
        op.execute("""
            CREATE OR REPLACE FUNCTION audit_logs_immutable() RETURNS trigger AS $$
            BEGIN
                RAISE EXCEPTION 'audit_logs is append-only';
            END;
            $$ LANGUAGE plpgsql;
        """)
        op.execute("""
            CREATE TRIGGER audit_logs_no_update_delete
            BEFORE UPDATE OR DELETE ON audit_logs
            FOR EACH ROW EXECUTE FUNCTION audit_logs_immutable();
        """)
    # ### end Alembic commands ###


def downgrade() -> None:
    if op.get_bind().dialect.name == "postgresql":
        op.execute("DROP TRIGGER IF EXISTS audit_logs_no_update_delete ON audit_logs")
        op.execute("DROP FUNCTION IF EXISTS audit_logs_immutable()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reviews_error_category'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_document_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_created_at'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_action'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_final_codes_document_id'), table_name='final_codes')
    op.drop_table('final_codes')
    op.drop_index(op.f('ix_coding_evidence_suggestion_id'), table_name='coding_evidence')
    op.drop_table('coding_evidence')
    op.drop_index('ix_suggestions_doc_status', table_name='coding_suggestions')
    op.drop_index(op.f('ix_coding_suggestions_validation_status'), table_name='coding_suggestions')
    op.drop_index(op.f('ix_coding_suggestions_status'), table_name='coding_suggestions')
    op.drop_index(op.f('ix_coding_suggestions_review_route'), table_name='coding_suggestions')
    op.drop_index(op.f('ix_coding_suggestions_document_id'), table_name='coding_suggestions')
    op.drop_index(op.f('ix_coding_suggestions_code'), table_name='coding_suggestions')
    op.drop_table('coding_suggestions')
    op.drop_index(op.f('ix_clinical_entities_document_id'), table_name='clinical_entities')
    op.drop_index(op.f('ix_clinical_entities_category'), table_name='clinical_entities')
    op.drop_table('clinical_entities')
    op.drop_index(op.f('ix_model_runs_document_id'), table_name='model_runs')
    op.drop_index(op.f('ix_model_runs_created_at'), table_name='model_runs')
    op.drop_table('model_runs')
    op.drop_index('ix_jobs_status_run_after', table_name='jobs')
    op.drop_index(op.f('ix_jobs_document_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_document_sections_document_id'), table_name='document_sections')
    op.drop_table('document_sections')
    op.drop_index(op.f('ix_documents_status'), table_name='documents')
    op.drop_index(op.f('ix_documents_sha256'), table_name='documents')
    op.drop_index(op.f('ix_documents_review_route'), table_name='documents')
    op.drop_index(op.f('ix_documents_external_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_api_keys_prefix'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('kb_versions')
    op.drop_index('ix_code_references_lookup', table_name='code_references')
    op.drop_index(op.f('ix_code_references_category'), table_name='code_references')
    op.drop_table('code_references')
    op.drop_index(op.f('ix_audit_logs_ts'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_document_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
